version: "3.7"

services:

  nginx:
    image: nginx:latest
    ports:
        - '${APP_PORT:-80}:80'
    volumes:
    - .:/var/www/html
    - ./docker/config/nginx:/etc/nginx/conf.d
    - ./docker/logs/nginx:/var/log/nginx
    links:
    - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
    ports:
    - 9000:9000
    volumes:
    - .:/var/www/html
    links:
    - database

  database:
      hostname: database
      image: mariadb:10
      restart: always
      ports:
          - '${FORWARD_DB_PORT:-3306}:3306'
      environment:
          MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
          MARIADB_ROOT_HOST: "%"
          MARIADB_DATABASE: '${DB_DATABASE}'
          MARIADB_USER: '${DB_USERNAME}'
          MARIADB_PASSWORD: '${DB_PASSWORD}'
          MARIADB_ALLOW_EMPTY_PASSWORD: 1
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      volumes:
          - ./docker/databases/mariadb:/var/lib/mysql
